# Generated by Django 3.1.1 on 2020-11-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='user_id',
            new_name='user',
        ),
    ]
